spring:
  application:
    name: "liquibase-demo"

  liquibase:
    change-log: "classpath:db/changelog/changelog-master.xml"

  datasource:
    url: "jdbc:mariadb://localhost:3306/liquibase"
    username: "root"
    password: "root"
    driver-class-name: "org.mariadb.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true


